model:
  # NOTE: 아래 명시된 config와 pth 경로 중 하나의 파일이라도 없을 경우 에러가 발생한다.
  - name: yolov5_m-p6
    config: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco.py
    pth: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco/best_ver4/ambulance_precision_epoch_90.pth

  - name: yolov8_l
    config: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov8_l_syncbn_fast_8xb16-500e_coco/yolov8_l_syncbn_fast_8xb16-500e_coco.py
    pth: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov8_l_syncbn_fast_8xb16-500e_coco/best_coco/bbox_mAP_epoch_300.pth

  - name: yolov8_x
    config: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov8_x_syncbn_fast_8xb16-500e_coco/yolov8_x_syncbn_fast_8xb16-500e_coco.py
    pth: /opt/ml/input/final-project-level3-cv-17/mmyolo/work_dirs/yolov8_x_syncbn_fast_8xb16-500e_coco/best_ver4/ambulance_precision_epoch_336.pth

inferenced: _inferenced

image:
  directory: /opt/ml/input/image/
  format:
    - .jpg
    - .png
    
video:
  directory: /opt/ml/input/video/
  format:
    - .mp4
    - .mkv

# 현재 서버에 input/output image가 저장되는 경로
image_input_path:
  path: /opt/ml/input/database/Images/Input

image_output_path:
  path: /opt/ml/input/database/Images/Output

server:
  host: 0.0.0.0
  port: 30001
